version: '3.8'

services:
  proxy:
    image: tasktimemanageproxy:dev
    container_name: tasktimemanage.proxy
    build:
      network: host
      context: ./src/Proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - react
      - WebUI
    networks:
      - TTM
  
  
  react:
    image: tasktimemanageweb:dev
    container_name: tasktimemanage.web
    restart: on-failure
    build:
      context: ./src/WebUI/TaskTimeManage.Web
    expose:
      - "80"
    stdin_open: true
    networks:
      - TTM
  
  WebUI:
    image: tasktimemanageapi:dev
    container_name: Tasktimemanage.WebUI
    build:
      context: .
      dockerfile: ./src/WebUI/Dockerfile
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - TTM
      - db
  
  postgres:
    image: postgres:latest
    container_name: tasktimemanage.db
    restart: always
    environment:
      - POSTGRES_DB=Tasktimemanage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fdGKhtr6dGJKG6byd5rFKuKJHGyvtfuhb6dFJKcr6utvygbhh76fu
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

networks:
  TTM:
    driver: bridge
  db:
    driver: bridge
volumes:
  db:
    driver: local 
