version: '3.8'

services:
  proxy:
    image: tasktimemanageproxy
    container_name: tasktimemanage.proxy
    build:
      context: ./TaskTimeManage.Proxy
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - front-tier
      - back-tier

  api:
    image: tasktimemanageapi
    container_name: Tasktimemanage.api
    build:
      context: .
      dockerfile: TaskTimeManage.Api/Dockerfile
    ports:
      - 433:433
    networks:
      - back-tier
      - db-tier
    depends_on:
      - tasktimemanage.db

  app:
    image: tasktimemanageapp
    container_name: tasktimemanage.app
    restart: on-failure
    build:
      context: ./TaskTimeManage.app
    ports:
      - 3000:3000
    networks:
      - front-tier
      - back-tier
    stdin_open: true
    volumes:
      - ./TaskTimeManage.app:/app
    command: npm start
    depends_on:
      - tasktimemanage.api
      
  db:
    image: postgres:latest
    container_name: tasktimemanage.db
    restart: always
    environment:
      - POSTGRES_DB=Tasktimemanage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fdGKhtr6dGJKG6byd5rFKuKJHGyvtfuhb6dFJKcr6utvygbhh76fu
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - db-tier
volumes:
  db:
    driver: local 
 
networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
  db-tier: {}