version: '3.8'

services:
  
  backend:
    image: tasktimemanageapi
    container_name: Tasktimemanage.api
    build:
      context: .
      dockerfile: TaskTimeManage.Api/Dockerfile
    ports:
      - 1337:1337
    depends_on:
      - postgres-db
    networks:
      - TTM  

  frontend:
    image: tasktimemanageapp
    container_name: tasktimemanage.app
    restart: on-failure
    build:
      context: ./TaskTimeManage.app
    ports:
      - 666:3000
    stdin_open: true
    volumes:
      - ./TaskTimeManage.app:/app
    command: npm start
    networks:
      - TTM  
      
  postgres-db:
    image: postgres:latest
    container_name: tasktimemanage.db
    restart: always
    environment:
      - POSTGRES_DB=Tasktimemanage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fdGKhtr6dGJKG6byd5rFKuKJHGyvtfuhb6dFJKcr6utvygbhh76fu
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - TTM  

networks:
  TTM:
    driver: bridge
volumes:
  db:
    driver: local 
