# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React-Web CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'src/WebUI/TaskTimeManage.Web/yarn.lock'

    - run: yarn install
      working-directory: src/WebUI/TaskTimeManage.Web
    - run: yarn run build
      working-directory: src/WebUI/TaskTimeManage.Web
    
    - name: Run lint
      run: yarn run lint --if-present
      working-directory: src/WebUI/TaskTimeManage.Web
